from PIL import Image
image=Image.open("example.jpg")
rotated_image=image.rotate(45)
image_1=Image.open("example.jpg")
RGB_image=image.convert("RGB")
red,green,blue=image.split()

coordinates_1=(25,0,671,522)
image_red=Image.open("red.jpg")
cropped_red1=image_red.crop(coordinates_1)
cropped_red1.save("1red.jpg")
coordinates_3=(50,0,696,522)
cropped_red2=image_red.crop(coordinates_3)
cropped_red2.save("2red.jpg")
image_red1=Image.open("1red.jpg")
image_red2=Image.open("2red.jpg")
image_red3=Image.blend(image_red1,image_red2,0.5)
image_red3.save("3red.jpg")

image_green=Image.open("green.jpg")
cropped_green=image_green.crop(coordinates_1)
cropped_green.save("3green.jpg")

image_blue=Image.open("blue.jpg")
cropped_blue1=image_blue.crop(coordinates_1)
cropped_blue1.save("1blue.jpg")
coordinates_2=(0,0,646,522)
cropped_blue2=image_blue.crop(coordinates_2)
cropped_blue2.save("2blue.jpg")
image_blue1=Image.open("1blue.jpg")
image_blue2=Image.open("2blue.jpg")
image_blue3=Image.blend(image_blue1,image_blue2,0.5)
image_blue3.save("3blue.jpg")

red=Image.open("3red.jpg")
green=Image.open("3green.jpg")
blue=Image.open("3blue.jpg")
image=Image.merge("RGB",(red,green,blue))
image.save("new_image.jpg")

new_image=Image.open("new_image.jpg")
new_image.thumbnail((80,80))
new_image.save("thumbnail.jpg")
